# Generated by Django 6.0.4 on 2026-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter each point on a new line')),
                ('technologies', models.CharField(help_text='Comma separated (e.g. Django, React, PostgreSQL)', max_length=200)),
                ('category', models.CharField(choices=[('fullstack', 'Full Stack'), ('backend', 'Backend'), ('api', 'API')], default='fullstack', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('source_code', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
